import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Choose Quiz",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning={true}>
                {/* true to suppressHydrationWarning due to its error sensitive
                related to our system extensions like grammarly */}
                <Nav />
                {children}
            </body>
        </html>
    );
}
